import React from "react";

/**
 * The Ghostly mark: a faceless ghost whose leftmost hem lobe stretches into a
 * trailing sweep — the descender gesture of the lowercase `g` the wordmark
 * spells out.
 *
 * Inline rather than an `<img>` so it inherits `currentColor` and stays crisp
 * at every size. The geometry is generated by `scripts/generate-icons.py`,
 * which is also the source of the app icon and the menu-bar glyphs; edit the
 * parameters there and re-run rather than hand-tuning this path.
 */
export const GhostlyMark: React.FC<
  React.SVGProps<SVGSVGElement> & { size?: number | string }
> = ({ size, width, height, className = "", ...props }) => (
  <svg
    viewBox="121 68 262 422.5"
    width={width ?? size}
    height={height ?? size}
    fill="none"
    role="presentation"
    className={className}
    {...props}
  >
    <path
      d="M 131.0 195.0 A 125.0 125.0 0 0 1 381.0 195.0 L 381.0 352.0 C 381.0 413.6 364.3 440.0 339.3 440.0 C 311.0 440.0 297.7 410.1 297.7 364.3 C 297.7 413.6 281.0 440.0 256.0 440.0 C 227.7 440.0 214.3 410.1 214.3 364.3 C 214.3 447.5 172.5 488.4 147.5 488.4 C 119.1 488.4 118.4 442.0 131.0 352.0 Z"
      fill="currentColor"
    />
  </svg>
);

export default GhostlyMark;
